/*
 * generated by Xtext 2.18.0
 */
package com.novomind.language.server


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ExpressionRuntimeModule extends AbstractExpressionRuntimeModule {
}
